version: '3'
services:
  db:
    container_name: mysql
    build: ./docker/mysql
    hostname: mysql
    ports:
      - "12000:12000"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql

  server:
    container_name: dnt-verify-server
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
